import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const yekanBakh = localFont({
  src: "./fonts/YekanBakh-Regular.ttf",
  variable: "--font-geist-sans",
});


export const metadata: Metadata = {
  title: "دوئل",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      suppressHydrationWarning
    >
      <body
        className={`${yekanBakh.className}`}
      >
        {children}
      </body>
    </html>
  );
}
